version: '3.9'
services:
  exchange-postgresql:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=exchange
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exchange
    ports:
      - "8932:5432"
    volumes:
      - ./exchange-core/src/main/resources/create-schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
